### ISSUE TITLE
Feature request: parse task list markdown

### ISSUE THREAD

**Issue by papernoise** [meltzow/deck-ng#20]
I would like to propose this feature: parsing of `- [ ]` to create todo/task lists.
The Nextcloud app does this, and even shows the number of tasks in the card.
I use t his a lot, so it would be really helpful to have deck-ng mirror the nextcloud app's behaviour.

**Comment by papernoise** [comment]
I just checked and my talk lists just render as normal unordered lists.

On the web app I see the list like this:

- [ ] task 1
- [ ] task 2

while on deck-ng I see it like this:

- task 1
- task 2

**Comment by meltzow** [comment]
With new version 1.3.0 its working. Happy new year
