### ISSUE TITLE
Add Support for due date

### ISSUE THREAD

**Issue by meltzow** [meltzow/deck-ng#33]

**Comment by meltzow** [comment]
- [ ] due date is selectable in issuedetails
- [ ] is overview/upcoming request reusable?
- [ ] display due date in boarddetails/ stacklists

**Comment by meltzow** [comment]
hi @bueroblanko
the current available version 1.4.0 supports setting due date now.
It will be great if you leave a positive rating or review for the app.

**Comment by bueroblanko** [comment]
Nice, thank you! I just did a rating on the appstore ;)
