### ISSUE TITLE
Display Issues on iOS

### ISSUE THREAD

**Issue by DerMusicus** [meltzow/deck-ng#44]
Hi there,
first thanks for starting an app tackling a major missing feature on mobile devices 😉 It’s a good start and helps me a lot getting myself and friends organised.

One thing that could be improved though is the displaying of some GUI elements. On my iPhone 13 with iOS 16.4.1 installed I noticed that I’m not able to hit the plus button to add new cards to my board. It is colliding with the top bar of my phone. Maybe some improvements could be done supporting the form faktoe of devices. Also the header description of my columns is cut off if it exceeds a small amount of characters. Maybe the width could be set dynamically by the header text.

Best regards,

Merlin

**Comment by meltzow** [comment]
thx for your feedback. Is it possible to attach a screenshot here?

**Comment by DerMusicus** [comment]
Hey,
Sure I will attach two examples.
Best regards,
Merlin
![IMG_3234](https://github.com/meltzow/deck-ng/assets/7570984/3acadc19-28dd-4c8c-8e5e-638e94053b08)
![IMG_3233](https://github.com/meltzow/deck-ng/assets/7570984/af4aedc4-fc29-497d-8b7d-b6761b5bddc8)

**Comment by meltzow** [comment]
great. now I understood. 
I will fix it in next release.
